#!/bin/bash

option="$1"
case $option in
    only)
        xrandr \
        --output DP2 --primary --mode 2560x1440 --scale .5x.5 \
        --output LVDS1 --off
        feh --bg-fill ~/wallpapers/fireworks.jpg
        ;;
    off)
        xrandr \
        --output LVDS1 --primary --mode 1366x768 \
        --output DP2 --off
        feh --bg-fill ~/wallpapers/fireworks.jpg
        ;;
    on)
        xrandr \
        --output LVDS1 --primary --mode 1366x768 \
        --output DP2 --mode 2560x1440 --above LVDS1 --scale .5x.5
        feh --bg-fill ~/wallpapers/fireworks.jpg
        ;;
    *)
        echo "set how to display to external monitor"
        echo "usage: extern [only | off | on]"
        exit 1
        ;;
esac
