#!/bin/bash

wallpaper="$HOME/wallpapers/colors.jpg"
option="$1"

case $option in
    only)
        xrandr \
        --output DP2 --primary --mode 2560x1440 --scale 1x1 \
        --output LVDS1 --off
        ;;
    off)
        xrandr \
        --output LVDS1 --primary --mode 1366x768 \
        --output DP2 --off
        ;;
    on)
        xrandr \
        --output LVDS1 --primary --mode 1366x768 \
        --output DP2 --mode 2560x1440 --above LVDS1 --scale 1x1
        ;;
    *)
        echo "set how to display to external monitor"
        echo "usage: extern [only | off | on]"
        exit 1
        ;;
esac

feh --bg-fill $wallpaper
