#!/bin/bash

cat << "EOF"
environment installation script

created by and designed personally for:

       __                                              
      /\ \                                             
      \_\ \     __      ___     ____  __  __    ___    
      /'_` \  /'__`\   / __`\  /',__\/\ \/\ \ /' _ `\  
     /\ \L\ \/\ \L\.\_/\ \L\ \/\__, `\ \ \_\ \/\ \/\ \ 
     \ \___,_\ \__/.\_\ \____/\/\____/\/`____ \ \_\ \_\
      \/__,_ /\/__/\/_/\/___/  \/___/  `/___/> \/_/\/_/
                                          /\___/       
                                          \/__/     

https://daosyn.info/about/
EOF

echo -e "\nstarting in a few seconds... press ctrl+c to quit\n"
sleep 5

# TODO check OS and install stuff using corresponding package manager
# right now, assuming Debian (apt)
packages='git vim gpg golang'

os=`uname -s`

# Debian
[ "$os" == "Linux" ] && \
sudo apt update && \
sudo apt install $packages -y

# macOS TODO

# openBSD TODO

# TODO set up GPG with SSH before continuing

echo -e "\nsetting up dotfiles and scripts...\n"
git clone --bare git@github.com:daosyn/dotfiles.git $HOME/.cfg
git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout -f
git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no
git clone git@github.com:daosyn/bin.git $HOME/bin

echo -e "\nsourcing .bashrc...\n"
. $HOME/.bashrc

echo -e "\ndone!\n"
