#!/bin/bash

monitor="$1"
case $monitor in
    on)
        xrandr \
        --output DP2 --primary --mode 2560x1440 \
        --output LVDS1 --off
        feh --bg-fill ~/wallpapers/fireworks.jpg
        ;;
    off)
        xrandr \
        --output LVDS1 --primary --mode 1366x768 \
        --output DP2 --off
        feh --bg-fill ~/wallpapers/fireworks.jpg
        ;;
    both)
        xrandr \
        --output LVDS1 --primary --mode 1366x768 \
        --output DP2 --mode 2560x1440 --above LVDS1
        feh --bg-fill ~/wallpapers/fireworks.jpg
        ;;
    *)
        echo "set which monitor(s) to display to"
        echo "usage: mon [on | off | both]"
        ;;
esac
