#!/bin/bash

if [ $# -ne 1 ]; then
    echo "create a new bash script"
    echo "usage: newbash [filename]"
    exit 1
else
    echo -e "#!/bin/bash\n\n" > $1
    chmod +x $1
    echo "executable file '$1' created"
    prompt=true
    while $prompt; do
        read -p "edit now? [y/n]: " -n 1 ans
        case $ans in
            y)
                prompt=false
                vim $1 +3
                ;;
            n)
                prompt=false
                ;;
            *)
                echo -e "\nplease respond with y or n"
                ;;
        esac
        echo
    done
fi
