#!/bin/bash

if [ $# -ne 1 ]; then
    echo "usage: post [title]"
else
    echo -e "---\nlayout: default\ntitle: $1\n---\n" > $(date +%F)-$1.md
    echo "post titled '$1' created"
    prompt=true
    while $prompt; do
        read -p "edit now? [y/n]: " -n 1 ans
        case $ans in
            y)
                prompt=false
                vim $(date +%F)-$1.md
                ;;
            n)
                prompt=false
                ;;
            *)
                echo -e "\nplease respond with y or n"
                ;;
        esac
        echo ""
    done
fi
